# tomcat accesslog option start
server.tomcat.accesslog.directory=E:/work/wroksapce/nope/logs

server.tomcat.accesslog.enabled=false
server.tomcat.accesslog.pattern=commona

server.tomcat.accesslog.prefix=pre
server.tomcat.accesslog.suffix=suf
# tomcat accesslog option end

# Database option start
# spring.datasource.driverClassName=
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
#Database option end

# Mybatis option start
# mybatis.type-aliases-package=me.eastglow.vo
# mybatis.configuration.map-underscore-to-camel-case=true
# mybatis.configuration.default-fetch-size=100
# mybatis.configuration.default-statement-timeout=30
# mybatis.mapper-locations=classpath:mapper/*.xml
# Mybatis option end

# exception start
#server.error.include-exception:false
# include-stacktrace : ALWAYS, NEVER, ON_TRACE_PARAM
#server.error.include-stacktrace:always
#server.error.path:/error
#server.error.whitelabel.enabled:false
# excpetion end

# ssl option start
# keytool -genkey -alias spring -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 4000
# server.ssl.key-store=keystore.p12
# server.ssl.key-store-type=PKCS12
# server.ssl.key-store-password=123456
# server.ssl.key-alias=spring
# server.http2.enabled=true
# ssl option end

nope.js.lang.path=/static/js/languages/
nope.js.lang.kor=kor.js

server.port=8888