DROP TABLE IF EXISTS NOPE_USER;
CREATE TABLE NOPE_USER (
	SEQ_ID		BIGINT			PRIMARY KEY,
	ACCOUNT		VARCHAR(500)	UNIQUE,
	PASSWORD	VARCHAR(1000)	NOT NULL,
	NICKNAME	VARCHAR(1000)	UNIQUE,
	SEX			CHAR(1)			CHECK (SEX IN ('F', 'M')),
	EMAIL		VARCHAR(1000)	NOT NULL,
	CREATE_DATE	TIMESTAMP		DEFAULT CURRENT_TIMESTAMP NOT NULL,
	MODIFY_DATE	TIMESTAMP		DEFAULT NULL,
	DELETE_DATE	TIMESTAMP		DEFAULT NULL,
	IS_DELETE	CHAR(1)			DEFAULT 'N' CHECK (IS_DELETE IN ('N', 'Y'))
);

DROP TABLE IF EXISTS NOPE_BOARD;
CREATE TABLE NOPE_BOARD (
	SEQ_ID			BIGINT			PRIMARY KEY,
	TITLE			VARCHAR(1000)	NOT NULL,
	WRITER			VARCHAR(500)	NOT NULL,
	VIEW_COUNT		INT				DEFAULT 0,
	FEIL_COUNT		INT				DEFAULT 0,
	CREATE_DATE		TIMESTAMP		CURRENT_TIMESTAMP,
	MODIFY_DATE		TIMESTAMP		DEFAULT NULL,
	DELETE_DATE		TIMESTAMP		DEFAULT NULL,
	IS_DELETE		CHAR(1)			DEFAULT 'N' CHECK (IS_DELETE IN ('Y', 'N')),
);

DROP TABLE IF EXISTS NOPE_BOARD_CONTENT;
CREATE TABLE NOPE_BOARD_CONTENT (
	SEQ_ID			BIGINT			PRIMARY KEY,
	BOARD_SEQ_ID	BIGINT			NOT NULL,
	CONTENT			TEXT			NOT NULL
);

DROP TABLE IF EXISTS NOPE_COMMENT;
CREATE TABLE NOPE_COMMENT (
	SEQ_ID			BIGINT			PRIMARY KEY,
	BOARD_SEQ_ID	BIGINT			NOT NULL,
	COMMENT_LEVEL	INT				DEFAULT 0,
	CONTENT			VARCHAR(1000)	NOT NULL,
	CREATE_DATE		TIMESTAMP		DEFAULT CURRENT_TIMESTAMP,
	MODIFY_DATE		TIMESTAMP		DEFAULT NULL,
	DELETE_DATE		TIMESTAMP		DEFAULT NULL,
	IS_DELETE		CHAR(1)			DEFAULT 'N' CHECK (IS_DELETE IN ('Y', 'N'))
);

DROP TABLE IF EXISTS NOPE_CERTIFICATION_MAIL;
CREATE TABLE NOPE_CERTIFICATION_MAIL (
	SEQ_ID				BIGINT			PRIMARY KEY,
	REUQEST_EMAIL		VARCHAR(1000)	NOT NULL,
	CERTIFICATION_CODE	VARCHAR(1000)	NOT NULL,
	EXPIRE_DATE			TIMESTAMP		DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS NOPE_CONFIG;
CREATE TABLE NOPE_CONFIG (
	CONFIG_KEY		VARCHAR(1000)	PRIMARY KEY,
	CONFIG_VALUE	VARCHAR(1000)	DEFAULT '',
	CREATE_DATE		TIMESTAMP		DEFAULT CURRENT_TIMESTAMP
	MODIFY_DATE		TIMESTAMP		DEFAULT NULL,
	IS_USE			CHAR(1)			DEFAULT 'Y' CHECK (IS_USER IN ('Y', 'N')),
	UNUSE_DATE		TIMESTAMP		DEFAULT NULL
);

DROP TABLE IF EXISTS NOPE_OVRESEAS_STOCK_COLLECT_LIST;
CREATE TABLE NOPE_OVRESEAS_STOCK_LIST (
	SEQ_ID			BIGINT			PRIMARY KEY,
	STOCK_CODE		VARCHAR(100)	NOT NULL UNIQUE,
	STOCK_NAME		VARCHAR(!0000)	NOT NULL,
	CREATE_DATE		TIMESTAMP		DEFAULT CURRENT_TIMESTAMP,
	IS_COLLECT		CHAR(1)			DEFAULT 'y' CHECK (IS_COLLECT IN ('Y', 'N'))
);

DROP TABLE IF EXISTS NOPE_OVRESEAS_STOCK;
CREATE TABLE NOPE_OVRESEAS_STOCK_DAILY (
	STOCK_CODE						VARCHAR(100)	NOT NULL,
	TARGET_DATE						DATE			NOT NULL,
	CLOSING_PRICE					INT				NOT NULL,
	HIGH_PRICE						INT				NOT NULL,
	LOW_PRICE						INT				NOT NULL,
	FLUCTUATION_PRICE				INT				NOT NULL,
	FLUCTUATION_RATIO				INT				NOT NULL,
	TOTAL_TRADING_VOLUME			INT				NOT NULL,
	INSTITUTIONAL_TRADING_VLOUME	INT				NOT NULL,
	FOREIGNER_TRADING_VLOUME		INT				NOT NULL,
	FOREIGNER_RETENTION_VLOUME		INT				NOT NULL,
	FOREIGNER_RETENTION_RATIO		INT				NOT NULL
);