DROP TABLE IF EXISTS REQUEST_CERTIFY;
CREATE TABLE IF NOT EXISTS REQUEST_CERTIFY (
    ID     			INTEGER GENERATED ALWAYS AS IDENTITY,
    REQUEST_EMAIL   VARCHAR NOT NULL,
    RESPONSE_CODE   VARCHAR NOT NULL,
    REQUEST_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	EXPIRE_DATE		TIMESTAMP DEFAULT CURRENT_TIMESTAMP + INTERVAL '3 MINUTES',
    IS_EXPIRE       VARCHAR DEFAULT 'N' CHECK (IS_EXPIRE IN ('Y', 'N'))
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE IF NOT EXISTS USERS (
    ID				INTEGER GENERATED ALWAYS AS IDENTITY,
	ACCOUNT			VARCHAR UNIQUE,
	PW				VARCHAR NOT NULL,
	SALT			VARCHAR NOT NULL,
	EMAIL			VARCHAR NOT NULL,
	ENROLL_DATE 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IS_DELETE		VARCHAR DEFAULT 'N' CHECK (IS_DELETE IN ('Y', 'N')),
	DELETE_DATE		TIMESTAMP DEFAULT NULL,
	LAST_LOGIN_IP	VARCHAR DEFAULT NULL
);

DROP TABLE IF EXISTS BOARD;
CREATE TABLE IF NOT EXISTS BOARD (
	ID			INTEGER GENERATED ALWAYS AS IDENTITY,
	TITLE		VARCHAR NOT NULL,
	PW			VARCHAR DEFAULT NULL,
	WRITER		INTEGER NOT NULL,
	WRITE_DATE	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFY_DATE TIMESTAMP DEFAULT NULL,
	IS_DELETE	VARCHAR DEFAULT 'N' CHECK (IS_DELETE IN ('Y', 'N')),
	DELETE_DATE	TIMESTAMP DEFAULT NULL,
	BOARD_TYPE	VARCHAR NOT NULL
);

DROP TABLE IF EXISTS REPLY;
CREATE TABLE IF NOT EXISTS REPLY (
	ID					INTEGER GENERATED ALWAYS AS IDENTITY,
	BOARD_ID			INTEGER NOT NULL,
	CONTENTS			TEXT NOT NULL,
	PARENT_REPLY_ID		INTEGER DEFAULT -1,
	REPLY_LEVEL			INTEGER DEFAULT 0,
	IS_DELETE			VARCHAR DEFAULT 'N' CHECK (IS_DELETE IN ('Y', 'N')),
	DELETE_DATE			TIMESTAMP DEFAULT NULL
);

DROP TABLE IF EXISTS ATTACH_FILE;
CREATE TABLE IF NOT EXISTS ATTACH_FILE (
	ID				INTEGER GENERATED ALWAYS AS IDENTITY,
	BOARD_ID		INTEGER NOT NULL,
	SAVE_NAME		VARCHAR NOT NULL,
	ORIGIN_NAME		VARCHAR NOT NULL,
	FILE_ORDER		INTEGER NOT NULL,
	IS_DELETE			VARCHAR DEFAULT 'N' CHECK (IS_DELETE IN ('Y', 'N')),
	DELETE_DATE			TIMESTAMP DEFAULT NULL
);

DROP TABLE IF EXISTS ROUTES;
CREATE TABLE IF NOT EXISTS ROUTES (
	ID				INTEGER GENERATED ALWAYS AS IDENTITY,
	BOARD_ID		INTEGER NOT NULL,
	COORDINATE		JSONB NOT NULL,
	IS_DELETE			VARCHAR DEFAULT 'N' CHECK (IS_DELETE IN ('Y', 'N')),
	DELETE_DATE			TIMESTAMP DEFAULT NULL
);

insert into users (account, pw, email, salt) values ('asdf', 'e65417289903d45997124f60df7dbf2cda688e17fc78ff1dfe70459f9f6949d6', 'aaaa@aaa.aa.aa', '1234');

insert into
	BOARD(TITLE, PW, WRITER, BOARD_TYPE)
values
	('test001', '', 1, 'AA'),
	('test002', '', 1, 'AA'),
	('test003', '', 1, 'AA'),
	('test004', '', 1, 'AA'),
	('test005', '', 1, 'AA');
	
commit;
